### PR TITLE
include tinytest tesing -- BASIC SETUP ONLY

### PR DESCRIPTION
**Pull request by jimrothstein**
## Description
This is TEST only.   Not Real PR.

basic setup for tinytest::

## Related Issue
first step in  #162

## Example
Goal:   Add tests of the form tinytest::expect_equal(1+1, 2) and similar.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @jimrothstein - want me to do anything? i just approved it so the checks can run

**Comment by jimrothstein** [comment]
@sckott   Thx.   Will continue now with a few tests, just wanted you to take look.   
Before I get too far, will ask you to take another look .... 
Thanks.

**Comment by jimrothstein** [comment]
Will do..

**Comment by jimrothstein** [comment]
@sckott 
Apologies ... gotten myself fouled up with git.
Can you delete this entire branch "jim" ?
I want start over.

**Comment by sckott** [comment]
@jimrothstein that branch is in your fork of the repo, not mine 😄

**Pull request closed without merging**
