### PR TITLE
setup-vcr.R -> helper-vcr.R

### PR DESCRIPTION
**Pull request by dpprdan**
This changes all references to setup-vcr.R to helper-vcr.R, as discussed in #244. `use_vcr()` also now creates a `helper-vcr.R` file. 

cc @maelle

### CODE REVIEW

**Comment by dpprdan** [comment]
I haven't rendered the README or the vignettes to avoid potential merge conflicts. 
Rendering the README also resulted in a lot of unrelated changes for me.

**Comment by sckott** [comment]
thanks @dpprdan  

@maelle can you take a look at this PR?

Do you think we should put this in this upcoming version to be submitted to CRAN? Or wait until the next version?

**Comment by maelle** [comment]
I can't take a closer look before Thursday but definitely agree on the principle!

**Comment by sckott** [comment]
@maelle okay, thanks. I'll see where I'm at wrt being ready to submit. If I'm ready to submit I don't want to wait too long as there's lots of pkg maintainers getting anxious about their pkgs being archived.

**Review by maelle — APPROVED** [review]
LGTM, thx a lot

**Pull request merged**
